
// This file has been generated by the GUI designer. Do not modify.
namespace catcher
{
	public partial class ListView
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget catcher.ListView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "catcher.ListView";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
